#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

do_one inlist_create_header planet_create_0.9685_MJ_5.0_RJ_10x_res.mod LOGS_create
do_one inlist_core_header planet_core_1.0_MJ_10.0_ME_5.0_RJ_10x_res.mod LOGS_core

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'

